[tool.poetry]
name = "gen"
version = "0.1.0"
description = ""
authors = ["Trim21 <i@trim21.me>"]

[tool.poetry.dependencies]
python = "^3.6"
pyyaml = "^5.3.1"
jinja2 = "^2.11.2"
pydantic = "^1.5"
yarl = "^1.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
