name: ci

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - uses: Trim21/setup-poetry@dist/v1

      - uses: Trim21/install-poetry-project@dist/v1

      - name: Generate Readme
        run: |
          mkdir -p dist
          python gen/gen.py > dist/readme.md
          echo "theme: jekyll-theme-cayman" > dist/_config.yml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: true
